# Generated by Django 3.2.11 on 2022-07-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
